# Generated by Django 6.0.5 on 2026-06-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Social_media.profile'),
        ),
    ]
