# Generated by Django 6.0.4 on 2026-06-04 01:46

import Social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0005_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[Social_media.models.validate_comment]),
        ),
    ]
