# Generated by Django 6.0.5 on 2026-06-07 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_media', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='Social_media.post'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
